spring.application.name=EcoCharge
external.carbonintensity.base-url=https://api.carbonintensity.org.uk/generation
external.frontend.allowed-origins=http://localhost:3000,https://eco-charge-frontend.onrender.com
